title: Sahil Singla
url: 'https://singlasahil14.github.io'
baseurl: ''

markdown: kramdown

# tracking_id: #

footer: no
footer_url: ''
footer_text: ''

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: 'Main'
   link: '/main/'
 - name: 'Resume'
   link: 'resume.pdf'
 - name: 'Contact'
   link: 'contact'
